### ISSUE TITLE
INVENTORY-SERVICE has a problem

### ISSUE THREAD

**Issue by damozhiying** [kbastani/spring-cloud-event-sourcing-example#11]
first ,thanks a lot ,
when i run INVENTORY-SERVICE local,
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "meta" (class org.neo4j.ogm.session.result.RowModelResult), not marked as ignorable (one known property: "row"])

**Comment by damozhiying** [comment]
--- maven-dependency-plugin:2.10:tree (default-cli) @ inventory-service ---
[INFO] org.kbastani:inventory-service:jar:0.0.1-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter:jar:1.3.3.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:1.3.3.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:1.3.3.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.3.3.RELEASE:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.1.5:compile
[INFO] |  |  |  - ch.qos.logback:logback-core:jar:1.1.5:compile
[INFO] |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.16:compile
[INFO] |  |  - org.slf4j:log4j-over-slf4j:jar:1.7.16:compile
[INFO] |  +- org.springframework:spring-core:jar:4.2.5.RELEASE:compile
[INFO] |  - org.yaml:snakeyaml:jar:1.16:runtime
[INFO] +- org.springframework.boot:spring-boot-starter-data-rest:jar:1.3.3.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-web:jar:1.3.3.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:1.3.3.RELEASE:compile
[INFO] |  |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.0.32:compile
[INFO] |  |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.0.32:compile
[INFO] |  |  |  +- org.apache.tomcat.embed:tomcat-embed-logging-juli:jar:8.0.32:compile
[INFO] |  |  |  - org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.0.32:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-validation:jar:1.3.3.RELEASE:compile
[INFO] |  |  |  - org.hibernate:hibernate-validator:jar:5.2.4.Final:compile
[INFO] |  |  |     +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  |     +- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO] |  |  |     - com.fasterxml:classmate:jar:1.1.0:compile
[INFO] |  |  +- org.springframework:spring-web:jar:4.2.5.RELEASE:compile
[INFO] |  |  - org.springframework:spring-webmvc:jar:4.2.5.RELEASE:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.5:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.5:compile
[INFO] |  |  - com.fasterxml.jackson.core:jackson-core:jar:2.6.5:compile
[INFO] |  - org.springframework.data:spring-data-rest-webmvc:jar:2.4.4.RELEASE:compile
[INFO] |     +- org.springframework.data:spring-data-rest-core:jar:2.4.4.RELEASE:compile
[INFO] |     |  +- org.springframework.hateoas:spring-hateoas:jar:0.19.0.RELEASE:compile
[INFO] |     |  +- org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE:compile
[INFO] |     |  - org.atteo:evo-inflector:jar:1.2.1:compile
[INFO] |     - com.github.fge:json-patch:jar:1.7:compile
[INFO] |        +- com.github.fge:jackson-coreutils:jar:1.6:compile
[INFO] |        |  - com.github.fge:msg-simple:jar:1.1:compile
[INFO] |        |     - com.github.fge:btf:jar:1.2:compile
[INFO] |        - com.google.code.findbugs:jsr305:jar:2.0.1:compile
[INFO] +- org.springframework.cloud:spring-cloud-starter-eureka:jar:1.1.0.RC1:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-starter:jar:1.1.0.RC2:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-context:jar:1.1.0.RC2:compile
[INFO] |  |  |  - org.springframework.security:spring-security-crypto:jar:4.0.3.RELEASE:compile
[INFO] |  |  - org.springframework.cloud:spring-cloud-commons:jar:1.1.0.RC2:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-netflix-core:jar:1.1.0.RC1:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-netflix-eureka-client:jar:1.1.0.RC1:compile
[INFO] |  +- com.netflix.eureka:eureka-client:jar:1.4.4:compile
[INFO] |  |  +- org.codehaus.jettison:jettison:jar:1.3.7:runtime
[INFO] |  |  |  - stax:stax-api:jar:1.0.1:runtime
[INFO] |  |  +- com.netflix.netflix-commons:netflix-eventbus:jar:0.3.0:runtime
[INFO] |  |  +- com.netflix.archaius:archaius-core:jar:0.7.3:compile
[INFO] |  |  +- javax.ws.rs:jsr311-api:jar:1.1.1:compile
[INFO] |  |  +- com.netflix.servo:servo-core:jar:0.10.1:runtime
[INFO] |  |  |  - com.netflix.servo:servo-internal:jar:0.10.1:runtime
[INFO] |  |  +- com.sun.jersey:jersey-core:jar:1.19.1:compile
[INFO] |  |  +- com.sun.jersey:jersey-client:jar:1.19.1:runtime
[INFO] |  |  +- com.sun.jersey.contribs:jersey-apache-client4:jar:1.19.1:runtime
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.1:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.4:compile
[INFO] |  |  |  - commons-codec:commons-codec:jar:1.9:compile
[INFO] |  |  +- com.google.inject:guice:jar:4.0:runtime
[INFO] |  |  |  +- javax.inject:javax.inject:jar:1:runtime
[INFO] |  |  |  - aopalliance:aopalliance:jar:1.0:compile
[INFO] |  |  - com.netflix.governator:governator-api:jar:1.12.10:runtime
[INFO] |  +- com.netflix.eureka:eureka-core:jar:1.4.4:compile
[INFO] |  |  +- com.amazonaws:aws-java-sdk-core:jar:1.10.30:runtime
[INFO] |  |  +- com.amazonaws:aws-java-sdk-ec2:jar:1.10.30:runtime
[INFO] |  |  +- com.amazonaws:aws-java-sdk-autoscaling:jar:1.9.3:runtime
[INFO] |  |  +- com.amazonaws:aws-java-sdk-sts:jar:1.9.3:runtime
[INFO] |  |  +- com.amazonaws:aws-java-sdk-route53:jar:1.9.3:runtime
[INFO] |  |  +- com.netflix.governator:governator:jar:1.12.10:runtime
[INFO] |  |  |  - com.netflix.governator:governator-core:jar:1.12.10:runtime
[INFO] |  |  - org.codehaus.woodstox:woodstox-core-asl:jar:4.4.1:runtime
[INFO] |  |     +- javax.xml.stream:stax-api:jar:1.0-2:runtime
[INFO] |  |     - org.codehaus.woodstox:stax2-api:jar:3.1.4:runtime
[INFO] |  +- org.springframework.cloud:spring-cloud-starter-archaius:jar:1.1.0.RC1:compile
[INFO] |  |  +- commons-configuration:commons-configuration:jar:1.8:compile
[INFO] |  |  |  - commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  |  - com.google.guava:guava:jar:18.0:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-starter-ribbon:jar:1.1.0.RC1:compile
[INFO] |  |  +- com.netflix.ribbon:ribbon:jar:2.1.3:compile
[INFO] |  |  |  +- com.netflix.ribbon:ribbon-transport:jar:2.1.3:runtime
[INFO] |  |  |  |  +- io.reactivex:rxnetty-contexts:jar:0.4.9:runtime
[INFO] |  |  |  |  - io.reactivex:rxnetty-servo:jar:0.4.9:runtime
[INFO] |  |  |  - io.reactivex:rxnetty:jar:0.4.9:runtime
[INFO] |  |  |     +- io.netty:netty-codec-http:jar:4.0.27.Final:runtime
[INFO] |  |  |     |  +- io.netty:netty-codec:jar:4.0.27.Final:runtime
[INFO] |  |  |     |  - io.netty:netty-handler:jar:4.0.27.Final:runtime
[INFO] |  |  |     - io.netty:netty-transport-native-epoll:jar:4.0.27.Final:runtime
[INFO] |  |  |        +- io.netty:netty-common:jar:4.0.27.Final:runtime
[INFO] |  |  |        +- io.netty:netty-buffer:jar:4.0.27.Final:runtime
[INFO] |  |  |        - io.netty:netty-transport:jar:4.0.27.Final:runtime
[INFO] |  |  +- com.netflix.ribbon:ribbon-core:jar:2.1.3:compile
[INFO] |  |  +- com.netflix.ribbon:ribbon-httpclient:jar:2.1.3:compile
[INFO] |  |  |  - com.netflix.netflix-commons:netflix-commons-util:jar:0.1.1:runtime
[INFO] |  |  +- com.netflix.ribbon:ribbon-loadbalancer:jar:2.1.3:compile
[INFO] |  |  |  - com.netflix.netflix-commons:netflix-statistics:jar:0.1.1:runtime
[INFO] |  |  - io.reactivex:rxjava:jar:1.0.14:compile
[INFO] |  +- com.netflix.ribbon:ribbon-eureka:jar:2.1.3:compile
[INFO] |  - com.thoughtworks.xstream:xstream:jar:1.4.2:compile
[INFO] |     +- xmlpull:xmlpull:jar:1.1.3.1:compile
[INFO] |     - xpp3:xpp3_min:jar:1.1.4c:compile
[INFO] +- org.springframework.cloud:spring-cloud-starter-hystrix:jar:1.1.0.RC1:compile
[INFO] |  +- com.netflix.hystrix:hystrix-core:jar:1.5.1:compile
[INFO] |  |  - org.hdrhistogram:HdrHistogram:jar:2.1.7:compile
[INFO] |  +- com.netflix.hystrix:hystrix-metrics-event-stream:jar:1.5.1:compile
[INFO] |  - com.netflix.hystrix:hystrix-javanica:jar:1.5.1:compile
[INFO] |     +- org.aspectj:aspectjweaver:jar:1.8.8:compile
[INFO] |     +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |     +- org.apache.commons:commons-lang3:jar:3.1:compile
[INFO] |     - org.ow2.asm:asm:jar:5.0.4:compile
[INFO] +- org.springframework.cloud:spring-cloud-starter-config:jar:1.1.0.RC1:compile
[INFO] |  - org.springframework.cloud:spring-cloud-config-client:jar:1.1.0.RC1:compile
[INFO] +- org.springframework.data:spring-data-neo4j:jar:4.0.0.RELEASE:compile
[INFO] |  +- org.neo4j:neo4j-ogm:jar:1.1.2:compile
[INFO] |  |  +- org.neo4j:neo4j:jar:2.2.5:compile
[INFO] |  |  |  +- org.neo4j:neo4j-kernel:jar:2.2.5:compile
[INFO] |  |  |  |  +- org.neo4j:neo4j-primitive-collections:jar:2.2.5:compile
[INFO] |  |  |  |  |  - org.neo4j:neo4j-unsafe:jar:2.2.5:compile
[INFO] |  |  |  |  +- org.neo4j:neo4j-io:jar:2.2.5:compile
[INFO] |  |  |  |  - org.neo4j:neo4j-csv:jar:2.2.5:compile
[INFO] |  |  |  +- org.neo4j:neo4j-lucene-index:jar:2.2.5:compile
[INFO] |  |  |  |  - org.apache.lucene:lucene-core:jar:3.6.2:compile
[INFO] |  |  |  +- org.neo4j:neo4j-graph-algo:jar:2.2.5:compile
[INFO] |  |  |  +- org.neo4j:neo4j-udc:jar:2.2.5:compile
[INFO] |  |  |  +- org.neo4j:neo4j-graph-matching:jar:2.2.5:compile
[INFO] |  |  |  +- org.neo4j:neo4j-cypher:jar:2.2.5:compile
[INFO] |  |  |  |  +- org.scala-lang:scala-library:jar:2.10.5:compile
[INFO] |  |  |  |  +- org.scala-lang:scala-reflect:jar:2.10.5:compile
[INFO] |  |  |  |  +- org.neo4j:neo4j-cypher-compiler-1.9:jar:2.0.4:compile
[INFO] |  |  |  |  +- org.neo4j:neo4j-cypher-compiler-2.0:jar:2.0.4:compile
[INFO] |  |  |  |  +- org.neo4j:neo4j-cypher-compiler-2.1:jar:2.1.8:compile
[INFO] |  |  |  |  +- org.neo4j:neo4j-cypher-compiler-2.2:jar:2.2.5:compile
[INFO] |  |  |  |  +- org.parboiled:parboiled-scala_2.10:jar:1.1.7:compile
[INFO] |  |  |  |  |  - org.parboiled:parboiled-core:jar:1.1.7:compile
[INFO] |  |  |  |  +- net.sf.opencsv:opencsv:jar:2.3:compile
[INFO] |  |  |  |  - com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar:1.4:compile
[INFO] |  |  |  +- org.neo4j:neo4j-jmx:jar:2.2.5:compile
[INFO] |  |  |  - org.neo4j:neo4j-consistency-check:jar:2.2.5:compile
[INFO] |  |  +- org.neo4j.app:neo4j-server:jar:2.2.5:compile
[INFO] |  |  |  +- org.neo4j:neo4j:pom:2.2.5:compile
[INFO] |  |  |  +- org.neo4j:server-api:jar:2.2.5:compile
[INFO] |  |  |  |  - org.neo4j.3rdparty.javax.ws.rs:jsr311-api:jar:1.1.2.r612:compile
[INFO] |  |  |  +- org.neo4j.app:neo4j-browser:jar:2.2.5:compile
[INFO] |  |  |  +- ch.qos.logback:logback-access:jar:1.1.5:compile
[INFO] |  |  |  +- org.codehaus.janino:janino:jar:2.7.8:compile
[INFO] |  |  |  |  - org.codehaus.janino:commons-compiler:jar:2.7.8:compile
[INFO] |  |  |  +- org.eclipse.jetty:jetty-server:jar:9.2.15.v20160210:compile
[INFO] |  |  |  |  +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  |  |  |  +- org.eclipse.jetty:jetty-http:jar:9.2.15.v20160210:compile
[INFO] |  |  |  |  |  - org.eclipse.jetty:jetty-util:jar:9.2.15.v20160210:compile
[INFO] |  |  |  |  - org.eclipse.jetty:jetty-io:jar:9.2.15.v20160210:compile
[INFO] |  |  |  +- org.eclipse.jetty:jetty-webapp:jar:9.2.15.v20160210:compile
[INFO] |  |  |  |  +- org.eclipse.jetty:jetty-xml:jar:9.2.15.v20160210:compile
[INFO] |  |  |  |  - org.eclipse.jetty:jetty-servlet:jar:9.2.15.v20160210:compile
[INFO] |  |  |  |     - org.eclipse.jetty:jetty-security:jar:9.2.15.v20160210:compile
[INFO] |  |  |  +- com.sun.jersey:jersey-server:jar:1.19.1:compile
[INFO] |  |  |  +- com.sun.jersey:jersey-servlet:jar:1.19.1:compile
[INFO] |  |  |  +- commons-digester:commons-digester:jar:2.1:compile
[INFO] |  |  |  |  - commons-beanutils:commons-beanutils:jar:1.9.2:compile
[INFO] |  |  |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  |  |  +- org.codehaus.jackson:jackson-jaxrs:jar:1.9.13:compile
[INFO] |  |  |  |  +- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] |  |  |  |  - org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |  |  |  +- org.rrd4j:rrd4j:jar:2.2:compile
[INFO] |  |  |  +- org.mozilla:rhino:jar:1.7R4:compile
[INFO] |  |  |  +- bouncycastle:bcprov-jdk16:jar:140:compile
[INFO] |  |  |  +- com.sun.jersey.contribs:jersey-multipart:jar:1.19:compile
[INFO] |  |  |  |  - org.jvnet.mimepull:mimepull:jar:1.9.3:compile
[INFO] |  |  |  - org.neo4j:neo4j-shell:jar:2.2.5:compile
[INFO] |  |  |     - org.apache.servicemix.bundles:org.apache.servicemix.bundles.jline:jar:0.9.94_1:compile
[INFO] |  |  - commons-lang:commons-lang:jar:2.6:compile
[INFO] |  +- org.springframework.data:spring-data-commons:jar:1.11.4.RELEASE:compile
[INFO] |  |  - org.springframework:spring-beans:jar:4.2.5.RELEASE:compile
[INFO] |  +- org.springframework:spring-context:jar:4.2.5.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:4.2.5.RELEASE:compile
[INFO] |  |  - org.springframework:spring-expression:jar:4.2.5.RELEASE:compile
[INFO] |  +- org.springframework:spring-tx:jar:4.2.5.RELEASE:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.16:compile
[INFO] |  - org.slf4j:jcl-over-slf4j:jar:1.7.16:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:1.3.3.RELEASE:test
[INFO] |  +- junit:junit:jar:4.12:test
[INFO] |  +- org.mockito:mockito-core:jar:1.10.19:test
[INFO] |  |  - org.objenesis:objenesis:jar:2.1:test
[INFO] |  +- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] |  +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] |  - org.springframework:spring-test:jar:4.2.5.RELEASE:test
[INFO] +- org.springframework.boot:spring-boot-configuration-processor:jar:1.3.3.RELEASE:compile
[INFO] |  - org.json:json:jar:20140107:compile
[INFO] - org.springframework.boot:spring-boot-starter-actuator:jar:1.3.3.RELEASE:compile
[INFO]    - org.springframework.boot:spring-boot-actuator:jar:1.3.3.RELEASE:compile
[INFO] ------------------------------------------------------------------------

**Comment by damozhiying** [comment]
I don't change anything about pom ,only mvn clean install -U ,then in eclipse ,i first run config-service ,discovery-service ,last run inventory-service,    above service not run in dock,  the local neo4j version is 3.0.4                 thank you very much ,help me  please

**Comment by kbastani** [comment]
Neo4j 3.0+ is not yet supported. Please use the version found in the docker compose file.
