### ISSUE TITLE
How does this example implement the event sourcing?

### ISSUE THREAD

**Issue by gyuwon** [kbastani/spring-cloud-event-sourcing-example#13]
How does this example implement event-sourcing? I found nothing about event-sourcing in this repository. Is there any magical thing?

**Comment by gyuwon** [comment]
Oh, at last I found `ShoppingCart` class. Event-sourcing is used in only some entities. Sorry.

**Comment by charsyam** [comment]
@gyuwon check this https://github.com/kbastani/spring-cloud-event-sourcing-example/tree/master/shopping-cart-service/src/main/java/demo
