### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by joachimgoo** [kbastani/spring-cloud-event-sourcing-example#14]
Hi

For some reason the servers are not able to call each other.
I always get a connection refused error when the online-store-web service tries to connect to the edge server.

Attached you will find my log files.

[startup.txt](https://github.com/kbastani/spring-cloud-event-sourcing-example/files/530494/startup.txt)
[log  online-store-web.txt](https://github.com/kbastani/spring-cloud-event-sourcing-example/files/530496/log.online-store-web.txt)

**Comment by marvinfontanilla14** [comment]
@joachimgoo ,hey bro, did you managed to resolved this issue? please let me know the work around. thank you so much!

**Comment by visusnet** [comment]
I'm having the (almost?) same issue. The difference in my logs is that I don't get this line:
```
discovery-service_1      | 2016-10-14 21:07:06.180  WARN 1 --- [nio-8761-exec-1] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/docker": Connection refused; nested exception is java.net.ConnectException: Connection refused
```
but this:
```
discovery-service_1      | 2017-03-21 09:32:49.604  INFO 1 --- [nio-8761-exec-1] c.c.c.ConfigServicePropertySourceLocator : Located environment: name=application, profiles=[docker], label=null, version=94accf174132f6d848a38726017461a82f7c9c54
discovery-service_1      | 2017-03-21 09:32:58.914  INFO 1 --- [nio-8761-exec-3] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://192.168.99.100:8888
discovery-service_1      | 2017-03-21 09:32:59.748  INFO 1 --- [nio-8761-exec-3] c.c.c.ConfigServicePropertySourceLocator : Located environment: name=application, profiles=[docker], label=null, version=94accf174132f6d848a38726017461a82f7c9c54
discovery-service_1      | 2017-03-21 09:33:00.116  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
discovery-service_1      | 2017-03-21 09:33:00.117  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
discovery-service_1      | 2017-03-21 09:33:00.117  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
discovery-service_1      | 2017-03-21 09:33:00.117  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application is null : false
discovery-service_1      | 2017-03-21 09:33:00.117  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
discovery-service_1      | 2017-03-21 09:33:00.117  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
discovery-service_1      | 2017-03-21 09:33:00.117  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
```

@marvinfontanilla14 @joachimgoo Were you able to resolve this issue?
@kbastani Do you know what could cause this?

Fortunately, everything still seems to work sometimes. What I saw is that the embedded Tomcat of the discovery-server is started after the discovery-server uses a DiscoveryClient to find itself. However, after a while, a retry will find it... sometimes. Sometimes means I didn't want to wait more than 5 minutes.

**Comment by restign** [comment]
I have only eight G memory, can not run it because of this problem？

**Comment by kbastani** [comment]
I'm not able to replicate the issue. I think that it's possible with 8GB of memory that the response times are too slow and hystrix is forcing timeouts on requests. I'll dig deeper and see if that resolves the issue.
