### ISSUE TITLE
maven clean install fails in inventory service

### ISSUE THREAD

**Issue by jangalinski** [kbastani/spring-cloud-event-sourcing-example#8]
Trying to run your (btw great!) tutorial, I fail when building the app:

> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configClientProperties' defined in org.springframework.cloud.config.client.ConfigServiceBootstrapConfiguration: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException

I am on master.

Do you have any ideas? Thanks!

**Comment by kbastani** [comment]
Can you please try using `mvn clean install -U`?
